pipeline {
  agent {
      label 'lxplus'
  }
  parameters {
     string(name: 'RunNumber', defaultValue: '')
  }
  environment {
        def run_number1 = params.RunNumber.substring(0, 3)
        def run_number2 = params.RunNumber.substring(3, 6)
  }
  stages {
    stage('Initialization') {
      steps {
        dir('1st-step_opt') {
	  buildName "Run${env.RunNumber}"
          buildDescription "Segment Extraolation analysis for ${env.BUILD_DISPLAY_NAME} executed @ ${NODE_NAME}"
          mattermostSend (
		color: "#2A42EE",
	 	message: "Build STARTED: ${env.JOB_NAME} (<${env.BUILD_URL}|${env.BUILD_DISPLAY_NAME}>)"
	  )
        }
      }
    }
    stage('Submit to condor') {
      steps {
	dir('SegmentExtrapolation-test') {
	  script {
	     sh "./submit_condor.sh ${run_number1} ${run_number2}"
	 }
      	}
      }
    }
    stage('Merge the output files') {
      steps {
	dir('SegmentExtrapolation-test') {
	script {
	sh "./merge.sh ${run_number1} ${run_number2}"
	  }
      	}
      }
    }
    stage('2nd step: calculate efficiency') {
      steps {
        dir('SegmentExtrapolation-test') {
        script {
        sh "./2nd.sh ${run_number1} ${run_number2}"
          }
        }
      }
    }
   stage('3nd step: make efficiency summary') {
      steps {
        dir('SegmentExtrapolation-test') {
        script {
        sh "./3rd.sh ${run_number1} ${run_number2}"
          }
        }
      }
    }
  }

 post {
        success {
            script {
                // Send a Mattermost notification when the build succeeds.
                mattermostSend(
                    color: 'good',
                    message: "Build SUCCESS: ${env.JOB_NAME} (<${env.BUILD_URL}|${env.BUILD_DISPLAY_NAME}>)"
                )
            }
        }
        
        failure {
            script {
                // Send a Mattermost notification when the build fails.
                mattermostSend(
                    color: 'danger',
                    message: "Build FAILED: ${env.JOB_NAME} (<${env.BUILD_URL}|${env.BUILD_DISPLAY_NAME}>)"
                )
            }
        }
    }
}
