pipeline {
  agent {
      label 'lxplus'
  }
  stages {
    stage('Initialization') {
      steps {
        dir('1st-step') {
          mattermostSend (
		color: "#2A42EE",
	 	message: "Build STARTED: ${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME} (<${env.BUILD_URL}|Link to build>)"
	  )
        }
      }
    }
    stage('Submit to condor') {
      steps {
	dir('1st-step') {
	  script {
	     sh "./submit_condor.sh"
	 }
      	}
      }
    }
   stage('Finalization') {
     steps {
        script {
           if(currentBuild.result == "FAILURE") {
                 mattermostSend (
                       color: "danger", 
                        message: "Build FAILED: ${env.JOB_NAME} #${env.BUILD_DISPLAY_NAME} (<${env.BUILD_URL}|Link to build>)"
                 )
           } else {
                 mattermostSend (
                       color: "good", 
                         message: "Build SUCCESS: ${env.JOB_NAME} #${env.BUILD_DISPLAY_NAME} (<${env.BUILD_URL}|Link to build>)"
                 )
          }
        }
      }
    }
  }
}
