pipeline {
  agent any
  stages {
    stage('version') {
      steps {
        sh 'python3 --version'
      }
    }
    stage('hello') {
      steps {
	dir('python4') {
        sh 'python3 hello.py'
        }
      }
    }
  }
}
