pipeline {
  agent {
      label 'lxplus'
  }
  stages {
    stage('Merge the output files') {
      steps {
	dir('merge_2nd_3rd') {
	sh '''
	./merge.sh
	'''
      	}
      }
    }
stage('2nd step: calculate efficiency') {
      steps {
        dir('merge_2nd_3rd') {
        sh '''
        ./2nd.sh
        '''
        }
      }
    }
stage('3nd step: make efficiency summary') {
      steps {
        dir('merge_2nd_3rd') {
        sh '''
        ./3rd.sh
        '''
        }
      }
    }
  }
}
