pipeline {
    agent {
        label 'python'
    }
    stages {
        stage('Run Python Script') {
            steps {
		dir('workflows/python1') {
                sh 'python3 myScript.py'
            }
          }
        }
    }
}
