pipeline {
  agent {
      label 'agent1'
  }
  stages {
    stage('version') {
      steps {
        sh 'python --version'
      }
    }
    stage('PWD') {
      steps {
        sh 'pwd'
      }
    }
    stage('hello') {
      steps {
	dir('python1') {
        sh 'python3 hello.py'
        }
      }
    }
  }
}
