pipeline {
  agent {
      label 'lxplus'
  }
  parameters {
	string(name: 'run_number', defaultValue: '')
  }
  stages {
    stage('Merge the output files') {
      steps {
	dir('merge_2nd_3rd_opt') {
	script {
	def run = params.run_number
	sh "echo $run"
	  }
      	}
      }
    }
stage('2nd step: calculate efficiency') {
      steps {
        dir('merge_2nd_3rd_opt') {
        sh """
	run=${params.run_number}
        ./2nd.sh ${run}
        """
        }
      }
    }
stage('3nd step: make efficiency summary') {
      steps {
        dir('merge_2nd_3rd_opt') {
        sh """
	run=${params.run_number}
        ./3rd.sh ${run}
        """
        }
      }
    }
  }
}
