pipeline {
  agent {
      label 'lxplus'
  }
  parameters {
	integer(name: 'run_number', defaultValue: '')
  }
  stages {
    stage('Merge the output files') {
      steps {
	dir('merge_2nd_3rd_opt') {
	sh """
 	int run = ${env.run_number}
	./merge.sh run
	"""
      	}
      }
    }
stage('2nd step: calculate efficiency') {
      steps {
        dir('merge_2nd_3rd_opt') {
        sh """
	int run = ${env.run_number}
        ./2nd.sh run
        """
        }
      }
    }
stage('3nd step: make efficiency summary') {
      steps {
        dir('merge_2nd_3rd_opt') {
        sh """
	int run = ${env.run_number}
        ./3rd.sh run
        """
        }
      }
    }
  }
}
