pipeline {
  agent {
      label 'lxplus'
  }
  parameters {
	string(name: 'run_number', defaultValue: '')
  }
  stages {
    stage('Merge the output files') {
      steps {
	dir('merge_2nd_3rd_opt') {
	sh '''
	./merge.sh ${env.run_number}
	'''
      	}
      }
    }
stage('2nd step: calculate efficiency') {
      steps {
        dir('merge_2nd_3rd_opt') {
        sh '''
        ./2nd.sh ${env.run_number}
        '''
        }
      }
    }
stage('3nd step: make efficiency summary') {
      steps {
        dir('merge_2nd_3rd_opt') {
        sh '''
        ./3rd.sh ${env.run_number}
        '''
        }
      }
    }
  }
}
