pipeline {
  agent {
      label 'lxplus'
    }

  stages {
    stage('Setup CMSSW Environment') {
      steps {
	dir('setup_cmssw') {
	script{
	def sshKeyCredentialId = 'GitLabSSH'
	sh './setup_cmssw.sh'
	  }
      	}
      }
    }
  }
}
